"""Конфигурация графического приложения Seeding."""

from __future__ import annotations

import os
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent

QSETTINGS_ORG = "SeedingApp"
QSETTINGS_APP = "Detector"

DEFAULT_WEIGHTS_PATH = Path(
    os.getenv(
        "YOLO_WEIGHTS_PATH",
        str(PROJECT_ROOT / "models" / "bestCrop.pt"),
    )
)
DEFAULT_CLASSIFY_WEIGHTS_PATH = Path(
    os.getenv(
        "YOLO_CLASSIFY_WEIGHTS_PATH",
        str(PROJECT_ROOT / "models" / "bestKlassSeg.pt"),
    )
)

DETECTION_CLASS_NAME = "seeding"
NMS_IOU_THRESHOLD = 0.4
DETECTION_CONFIDENCE_THRESHOLD = 0.25
DETECTION_IOU_THRESHOLD = NMS_IOU_THRESHOLD

CONF_THRESHOLD_HIGH = 0.9
CONF_THRESHOLD_LOW = 0.5

ROTATE_K = -1
ROTATE_ANGLE_DEG = 90
CALIBRATION_PIXELS_PER_MM_DEFAULT = 0.0

WINDOW_X = 100
WINDOW_Y = 100
WINDOW_WIDTH = 1400
WINDOW_HEIGHT = 900
SPLITTER_SIZES = [280, 920, 380]
PANEL_LAYERS_MIN_WIDTH = 280
PANEL_LAYERS_MAX_WIDTH = 420
ZOOM_FACTOR_INCREMENT = 1.25

PDF_JPEG_QUALITY = 70
PDF_IMAGE_MAX_WIDTH_MM = 160
PDF_IMAGE_MAX_HEIGHT_MM = 200
PDF_CROP_MAX_WIDTH_MM = 60
PDF_CROP_MAX_HEIGHT_MM = 80
PDF_SPACER_MM = 5
PDF_CROPS_PER_PAGE = 3
PDF_BBOX_COLOR_MAIN = (0, 255, 0)
PDF_BBOX_COLOR_CLASS = (255, 0, 0)
PDF_BBOX_THICKNESS = 2
PDF_FONT_SCALE = 0.8
PDF_LABEL_OFFSET_Y = 5
PDF_RENDER_SCALE_DEFAULT = 4.0

BBOX_COLOR_ORANGE_RGB = (255, 165, 0)
UI_BBOX_PEN_WIDTH = 5
UI_BBOX_LABEL_FONT_POINT_SIZE = 11
UI_BBOX_LABEL_FONT_PIXEL_SIZE = 15

APP_FONT_FAMILY = "Segoe UI"
APP_FONT_SIZE = 10
